export function renderFooter(): HTMLElement {
  const footer = document.createElement('footer');
  footer.className = 'footer';
  
  footer.innerHTML = `
    <div class="container footer__inner">
      <div class="footer__brand-col">
        <div class="footer__brand">
          <img src="/assets/ashoka-chakra.png" alt="" width="24" height="24" style="margin-right: 8px; opacity: 0.8;"/>
          Indian Election Assistant
        </div>
        <p class="footer__tagline">Educational guide for the electoral process</p>
        <div class="footer__helpline">
          <strong>Voter Helpline:</strong> <a href="tel:1950">1950</a>
        </div>
      </div>
      
      <div class="footer__links-col">
        <h4 class="footer__heading">Official Links</h4>
        <div class="footer__links">
          <a href="https://eci.gov.in" target="_blank" rel="noopener" class="footer__link">Election Commission of India (ECI)</a>
          <a href="https://voters.eci.gov.in" target="_blank" rel="noopener" class="footer__link">Voter Portal</a>
          <a href="https://nvsp.in" target="_blank" rel="noopener" class="footer__link">NVSP</a>
        </div>
      </div>
    </div>
    <div class="container">
      <p class="footer__disclaimer">
        This tool provides general information about the Indian election process for educational purposes. 
        It is not affiliated with the ECI or any government agency. AI responses are generated by Google Gemini and may not always be accurate.
        Always verify critical information at <a href="https://eci.gov.in" target="_blank" rel="noopener">eci.gov.in</a>.
      </p>
    </div>
  `;

  return footer;
}
