export function renderAboutPage(): HTMLElement {
  const page = document.createElement('div');
  page.className = 'page-container';

  page.innerHTML = `
    <section class="section section--visible">
      <div class="container">
        <div class="section__header">
          <div class="section__badge">
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
              <circle cx="12" cy="12" r="10"/>
              <line x1="12" y1="16" x2="12" y2="12"/>
              <line x1="12" y1="8" x2="12.01" y2="8"/>
            </svg>
            About This Tool
          </div>
          <h1 class="section__title">About Indian Election Assistant</h1>
          <p class="section__subtitle">
            An educational tool to help citizens understand the Indian electoral process.
          </p>
        </div>

        <div class="info-cards">
          <div class="info-card">
            <div class="info-card__icon">⚠️</div>
            <h3 class="info-card__title">Disclaimer</h3>
            <p class="info-card__text">
              This tool provides <strong>general educational information</strong> about Indian elections.
              It is <strong>not affiliated with the Election Commission of India</strong> or any government agency.
              AI responses are generated by Google Gemini and may not always be accurate or up-to-date.
              Always verify critical information at 
              <a href="https://eci.gov.in" target="_blank" rel="noopener">eci.gov.in</a>.
            </p>
          </div>

          <div class="info-card">
            <div class="info-card__icon">🔍</div>
            <h3 class="info-card__title">Coverage Scope</h3>
            <p class="info-card__text">
              This tool covers elections conducted by the <strong>Election Commission of India</strong>:
              Lok Sabha, Rajya Sabha, State Legislative Assemblies, Presidential, and Vice Presidential elections.
              <strong>Panchayat and Municipal elections</strong> are governed by State Election Commissions 
              and are outside the scope of this tool.
            </p>
          </div>

          <div class="info-card">
            <div class="info-card__icon">🤖</div>
            <h3 class="info-card__title">AI Limitations</h3>
            <p class="info-card__text">
              The AI assistant is designed to be neutral and factual. It will not express political opinions
              or endorse any party or candidate. It may occasionally provide outdated information — 
              always cross-reference with official ECI sources. Hindi language input is supported.
            </p>
          </div>

          <div class="info-card">
            <div class="info-card__icon">📌</div>
            <h3 class="info-card__title">Official Sources</h3>
            <p class="info-card__text">
              All information is based on publicly available data from:
              <a href="https://eci.gov.in" target="_blank" rel="noopener">eci.gov.in</a>,
              <a href="https://voters.eci.gov.in" target="_blank" rel="noopener">voters.eci.gov.in</a>,
              <a href="https://nvsp.in" target="_blank" rel="noopener">nvsp.in</a>, and the
              <strong>1950 Voter Helpline</strong>.
            </p>
          </div>
        </div>
      </div>
    </section>
  `;

  return page;
}
